name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE ($URL)'
categories:
  - title: '🚀 Features'
    labels: 'feature'
  - title: '🌈 Data Update'
    labels: 'data update'
  - title: '🔨 Improvements'
    labels:
      - 'improvement'
      - 'documentation'
      - 'dependencies'
  - title: '🐛 Bug Fixes'
    labels: 'bug'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  $CHANGES
