version: 2
jobs:
  check:
    docker:
      - image: circleci/node:14.15.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore dependencies cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Format
          command: yarn format
      - run:
          name: Check type
          command: yarn type-check
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
      - run:
          name: Check data
          command: yarn generate-data && test `git status -s src/data/* | wc -l` = 0 || (echo Generate and commit the latest data! && false)
      - run:
          name: Build
          command: yarn build
      - run:
          name: Lighthouse
          command: yarn lighthouse
      - save_cache:
          name: Save dependencies cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  build-deploy:
    docker:
      - image: circleci/node:14.15.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore dependencies cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Set up GitHub user name
          command: git config user.name $GITHUB_NAME
      - run:
          name: Set up GitHub user email
          command: git config user.email $GITHUB_EMAIL
      - run:
          name: Deploy
          command: yarn deploy
      - save_cache:
          name: Save dependencies Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
workflows:
  version: 2
  deploy:
    jobs:
      - check
      - build-deploy:
          requires:
            - check
          filters:
            branches:
              only: master
