version: 2
jobs:
  check:
    docker:
      - image: circleci/node:14.15.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore dependencies cache
          keys:
            - npm-packages-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Format
          command: npm run format
      - run:
          name: Check type
          command: npm run type-check
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test
      - run:
          name: Check data
          command: npm run generate-data && test `git status -s src/data/* | wc -l` = 0 || (echo Generate and commit the latest data! && false)
      - run:
          name: Build
          command: npm run build
      - save_cache:
          name: Save dependencies cache
          key: npm-packages-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/npm
workflows:
  version: 2
  deploy:
    jobs:
      - check
